# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AgentBlackAndWhiteApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AgentBlackAndWhiteApp

  target 'AgentBlackAndWhiteAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AgentBlackAndWhiteAppUITests' do
    # Pods for testing
  end
pod 'Firebase/Database'
pod 'Firebase/Auth'
end
